#!/usr/bin/env sh

if [ $# == 1 ] && [ $1 == "examples" ]; then
  for f in `git ls-files *.go`; do
    if [ $f == "to.go" ] || [ $f == "from.go" ] || [ $f == "blend.go" ]; then
      echo "skipping $f..."
    else
      echo "running $f..."
      go run $f < "examples/original.png" | to "examples/${f%.*}.jpg"
    fi
  done

  # run blend.go
  echo "running blend.go..."

  if [ ! -d "blend-tmp" ]; then
    mkdir "blend-tmp"
  fi

  for m in `go run blend.go --modes`; do
    echo "  $m..."
    go run blend.go --$m "examples/trans.png" < "examples/original.png" | to "blend-tmp/$m.jpg"
  done

  modelist=blend-tmp/{$(echo `go run blend.go --modes` | sed 's/\ /,/g')}.jpg
  eval montage -label "%t" $modelist -geometry 134x200+4+3 "examples/blend.jpg"
  rm -r "blend-tmp"

  # create composed image
  echo "creating composed example..."
  go run shuffle.go --horizontal < "examples/original.png" | go run hxl.go | go run hue.go --by -20 | to "examples/composed.jpg"

  # create hsl composite image
  echo "creating hsl image..."
  montage examples/{hue,saturation,lightness}.jpg -geometry +5+0 "examples/hsl.jpg"
  rm examples/{hue,saturation,lightness}.jpg

else
  if [ ! -d "built" ]; then
    mkdir "built"
  fi

  for f in `git ls-files *.go`; do
    echo "Building ${f%.*}"
    go build -o "built/${f%.*}" "${f}"
  done
fi
